package CalcApp;


/**
* CalcApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, 10 May, 2026 4:14:25 PM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int subtract (int a, int b);
  int multiply (int a, int b);
  float divide (int a, int b);
} // interface CalculatorOperations
